sudo: required
services:
  - docker

before_install:
  - docker build -t tarak99/app-test ./app

script:
  - docker run -e CI=true tarak99/app-test npm test

after_success:
  - docker build -t tarak99/app ./app
